[package]
name = "pcti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.4"
serde = "1.0.163"
serde_derive = "1.0.163"
image = "0.24.6"
rand = "0.8.5"
